version : '3.8'
services:
  episen-sca-ape-back:
    image: andreipetrov/episen-sca-ape-back
    container_name: episen-sca-ape-back-container
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
    - /Users/pluton/tpsca/episen-sca-ape-tp4/back:/log4j
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  episen-sca-ape-front:
    image: andreipetrov/episen-sca-ape-front
    container_name: episen-sca-ape-front-container
    expose:
      - 4200
    ports:
      - "4200:4200"
    links:
      - episen-sca-ape-back
    restart: always
    volumes:
    - /Users/pluton/tpsca/episen-sca-ape-tp4/front:/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/4200"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 3
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

